language: php

matrix:
  fast_finish: true
  include:
    - php: 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install -n

script:
  - vendor/bin/phpunit

sudo: false
